Repository DOoO0OL/HOTSPOT-Server, pull requests merged in 2023-12, with the labels that each got.

#10 🔀 :: 토큰 재발급 API
  hotspot-api/src/main/kotlin/com/dol/domain/auth/exception/ExpiredRefreshTokenException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/presentation/AuthController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/TokenReissueService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/impl/TokenReissueServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/auth/entity/RefreshToken.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#12 마이페이지 API
  hotspot-api/src/main/kotlin/com/dol/common/util/UserUtil.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/presentation/UserController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/presentation/data/response/MyPageResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/presentation/data/response/TokenDto.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/service/MyPageService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/service/impl/MyPageServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#15 14 feat/set entity
  build.gradle.kts
  hotspot-api/build.gradle.kts
  hotspot-api/src/main/kotlin/com/dol/global/security/jwt/TokenParser.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/principal/AdminDetails.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/principal/AdminDetailsService.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/principal/UserDetails.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/principal/UserDetailsService.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/follow/entity/Follow.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/entity/Hotplace.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/recommend/entity/Recommend.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/user/entity/User.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/user/enums/Authority.kt
Labels: 0️⃣ Priority: Critical

#16 🔀 :: 로그아웃 API
  hotspot-api/src/main/kotlin/com/dol/domain/auth/presentation/AuthController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/LogoutService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/impl/LogoutServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#20 🔀 :: 팔로우 취소 API
  hotspot-api/build.gradle.kts
  hotspot-api/src/main/kotlin/com/dol/domain/follow/presentation/FollowController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/follow/service/FollowCancelService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/follow/service/impl/FollowCancelServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/config/QueryDslConfig.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/build.gradle.kts
  hotspot-domain/src/main/kotlin/com/dol/domain/follow/repository/custom/CustomFollowRepository.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/follow/repository/custom/impl/CustomFollowRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#22 🔀 :: coolsms 인증번호 전송 API
  build.gradle.kts
  hotspot-api/src/main/kotlin/com/dol/common/util/AuthUtil.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/exception/AuthenticationNotFoundException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/exception/ManyAuthenticationRequestException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/presentation/AuthController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/SendAuthCodeService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/impl/SendAuthCodeServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/config/PropertiesScanConfig.kt
  hotspot-api/src/main/kotlin/com/dol/global/error/ErrorStatus.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/coolSms/exception/MessageSendFailedException.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/coolSms/properties/CoolSmsProperties.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/coolSms/sender/CoolSmsSender.kt
  hotspot-api/src/main/resources/application.yml
  hotspot-domain/src/main/kotlin/com/dol/domain/auth/entity/AuthCode.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/auth/entity/Authentication.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/auth/repository/AuthCodeRepository.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/auth/repository/AuthenticationRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#24 🔀 :: 인증번호 검증 API
  hotspot-api/src/main/kotlin/com/dol/common/util/AuthUtil.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/exception/AuthCodeNotFoundException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/exception/AuthCodeNotMatchException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/presentation/AuthController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/VerifyAuthCodeService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/impl/SendAuthCodeServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/domain/auth/service/impl/VerifyAuthCodeServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/error/ErrorStatus.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#27 🔀 :: 프로필 필드 추가
  hotspot-api/src/main/kotlin/com/dol/domain/user/presentation/data/response/MyPageResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/service/impl/MyPageServiceImpl.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#28 🔀 :: 팔로우 추천 API
  hotspot-api/src/main/kotlin/com/dol/domain/follow/presentation/FollowController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/follow/presentation/data/response/FollowRecommendResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/follow/service/FollowRecommendService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/follow/service/impl/FollowRecommendServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#31 🔀 :: 엔티티 필드 추가 및 삭제
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/entity/Hotplace.kt
Labels: 0️⃣ Priority: Critical

#32 🔀 :: 사진 업로드 API
  hotspot-api/build.gradle.kts
  hotspot-api/src/main/kotlin/com/dol/domain/image/presentation/ImageController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/image/presentation/data/response/ImageUrlResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/image/service/ImageUploadService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/image/service/impl/ImageUploadServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/config/PropertiesScanConfig.kt
  hotspot-api/src/main/kotlin/com/dol/global/error/ErrorStatus.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/aws/AwsConfig.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/aws/exception/FailedFileUploadException.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/aws/properties/AwsProperties.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/aws/properties/s3/AwsS3Properties.kt
  hotspot-api/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#36 🔀 :: 프로필 이미지 변경 API
  hotspot-api/src/main/kotlin/com/dol/domain/image/presentation/ImageController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/image/service/impl/ImageUploadServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/presentation/UserController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/service/UploadProfileImageService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/user/service/impl/UploadProfileImageServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/user/entity/User.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#37 🔀 :: hotplace 생성 API
  hotspot-api/src/main/kotlin/com/dol/HotspotApplication.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/HotplaceController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/data/request/CreateHotplaceRequest.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/CreateHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/CreateHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/config/PropertiesScanConfig.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/kakao/properties/KakaoProperties.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/kakao/util/KakaoUtil.kt
  hotspot-api/src/main/resources/application.yml
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/entity/Hotplace.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/enums/ApproveStatus.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/repository/HotplaceRepository.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#39 🔀 :: hotplace 조회 API
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/exception/HotplaceNotFoundException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/HotplaceController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/data/response/QueryHotplaceResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/QueryHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/QueryHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/error/ErrorStatus.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/entity/Hotplace.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/repository/HotplaceRepository.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/recommend/repository/RecommendRepository.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#41 🔀 :: 핫플레이스 추천 API
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/exception/AlreadyRecommendedHotplaceException.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/HotplaceController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/RecommendHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/RecommendHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/error/ErrorStatus.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/recommend/entity/Recommend.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/recommend/repository/RecommendRepository.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#43 42 🔀 :: 핫플레이스 리스트 API
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/HotplaceController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/data/request/QueryHotplaceListRequest.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/data/response/QueryHotplaceListResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/QueryHotplaceListService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/CreateHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/QueryHotplaceListServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/thirdparty/kakao/util/KakaoUtil.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/entity/Hotplace.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/repository/HotplaceRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#45 🔀 :: 44 자신이 추천한 핫플레이스 리스트 API
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/HotplaceController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/presentation/data/response/QueryRecommendedHotplaceResponse.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/QueryRecommendedHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/hotplace/service/impl/QueryRecommendedHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/repository/HotplaceRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#47 🔀 :: 46 핫플레이스 승인 API
  hotspot-api/src/main/kotlin/com/dol/domain/admin/presentation/AdminController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/admin/service/ApproveHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/admin/service/impl/ApproveHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#50 🔀 :: 49 핫플레이스 거절 API
  hotspot-api/src/main/kotlin/com/dol/domain/admin/presentation/AdminController.kt
  hotspot-api/src/main/kotlin/com/dol/domain/admin/service/RejectHotplaceService.kt
  hotspot-api/src/main/kotlin/com/dol/domain/admin/service/impl/RejectHotplaceServiceImpl.kt
  hotspot-api/src/main/kotlin/com/dol/global/security/SecurityConfig.kt
  hotspot-domain/src/main/kotlin/com/dol/domain/hotplace/enums/ApproveStatus.kt
Labels: 1️⃣ Priority: High, ✨ Feature
